---                                                                                                                     
- hosts: mineservers
  vars_files:
  - ../vars.yml
  vars:
    fileName: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}.{{ansible_date_time.epoch}}.zip"
  tasks:
  - debug:
      msg: "File name is {{ fileName }}"
      
  - name: Compress world
    archive:
      path: "{{ world_location }}"
      dest: "/home/mine/{{ fileName }}"
      format: zip
      
  - name: Download backup
    fetch:
      src: "/home/mine/{{ fileName }}"
      dest: "./backups/{{ fileName }}"
      flat: yes
